### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by iKalentii** [Astwix/VectorEditor#1]
Т.к. не могу пул кинуть или коммитить - вот файлы с замечаниями.

[GRASP_7.docx](https://github.com/Astwix/VectorEditor/files/3212821/GRASP_7.docx)
[GRASP_lc_hc.docx](https://github.com/Astwix/VectorEditor/files/3212822/GRASP_lc_hc.docx)

**Comment by Astwix** [comment]
Исправлены: https://github.com/Astwix/VectorEditor/commit/0ac391e25cc0569f07b9d5297f42ef28bd7a1e52
